### ISSUE TITLE
Should require video clips

### ISSUE THREAD

**Issue by kormoc** [TrumpTracker/trumptracker.github.io#1]
Each policy should have a video clip of the promise

**Comment by subdavis** [comment]
I think fact checking in general needs work.  I'm not sure video is possible though, as many came from rallies that were not recorded, or journalist interviews. That requirement might be overly stringent.

Check out #2 as well.

**Comment by aflashyrhetoric** [comment]
Agreed, I think that video is excessive but I do agree that the quality of this entire project hinges on the reliability of the promises. Definitely a core concern. At the very least, it should be sourced in some way from a "reliable" news source.

**Comment by MrLuit** [comment]
I'm closing this issue because it's very hard to find a youtube video for each policy. We'll add youtube video's where we can, once #2 is finished.

Please refer to #2.

**Comment by VirenMohindra** [comment]
Let's keep it open, so we don't forget about this?

**Comment by aflashyrhetoric** [comment]
I don't think this should stay open in its current form - burden of proof is definitely on the claimant, but video for every single claim will be very hard. In other words, source is necessary but video is not.

**Comment by VirenMohindra** [comment]
latest issue for this is #69 which is in progress. Thank you!
