### ISSUE TITLE
Make it dynamic

### ISSUE THREAD

**Issue by alanfriedman** [TrumpTracker/trumptracker.github.io#11]
This is great but like you said, would benefit from not having everything hard-coded. I'd suggest a simple static site generator like Jekyll with the "promises" being pulled from a JSON list.

I'm happy to submit a PR if you're interested in taking that route.

**Comment by VirenMohindra** [comment]
This is a great idea. I would love to have a PR if you can implement this!

**Comment by thedotmack** [comment]
I would love to see this data in JSON format, it would allow everyone to build some really interesting things from it. 

We could probably easily scrape it out of here :)

**Comment by jayrav13** [comment]
Happy to contribute to this! +1

**Comment by VirenMohindra** [comment]
Every policy is under a `<table class="table">` > `<tbody>` > `<td>`

If someone does scrape it, please push the `.json` onto this repo. I'll merge it!
