### ISSUE TITLE
Make it so users can sort by date achieved?

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#114]
### Description of your *issue*, suggested solution and other information

This could be useful. It would make it easier to track changes from day to day, as many times I go on the page only to realize I don't know what is new and what was already there.
Just a suggestion, not sure how easy/hard it would be to implement, if possible at all.

by /u/Onlyusemeusername from /r/trumptracker

---

### Make sure you are using the *latest* version: pull latest commits before reporting any issues.
- [x] I've **verified** and **I assure** that I'm looking at the latest version of Trump Tracker.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) section.
- [x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the trumptracker website)
- [ ] Site support request (request for adding support)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

**Comment by VirenMohindra** [comment]
This could be a neat feature, with another line in the dashboard where you can click on it and it'll sort every data-facet by the `dateModified` category. you could also type in the date in some format and it'll filter it out.

Thoughts?

**Comment by MrLuit** [comment]
I honestly do not see why users would want to sort specifically on achieved date, although the concept of sorting the items could be useful.

**Comment by captainfedora** [comment]
I would like to see this implemented if possible, it could help see how progress was made over time

**Comment by MrLuit** [comment]
Merged with #63
