### ISSUE TITLE
Add a delayed section

### ISSUE THREAD

**Issue by ncovercash** [TrumpTracker/trumptracker.github.io#117]
### Description of your *issue*, suggested solution and other information

I would like a way to show if the goal was still accomplished, despite that it wasn't on the first day in office.  For example, #86 is under progress currently, but was not accomplished on the first day in office.  If it is accomplished, adding a way to show #86 as not _broken_, but delayed would be helpful

### Make sure you are using the *latest* version: pull latest commits before reporting any issues.
- [x] I've **verified** and **I assure** that I'm looking at the latest version of Trump Tracker.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) section.
-[x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the trumptracker website)
- [ ] Site support request (request for adding support)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

And as always, thank you for your contribution.

**Comment by MrLuit** [comment]
What you are describing right now would fall under the 'Compromised' category. If we are going to create a new tag for every situation it would be more complicated for the user.

**Comment by ncovercash** [comment]
Alright, thanks.  I'll go ahead and close this then.
