### ISSUE TITLE
Bill undoing Obama coal mining rule

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#119]
### Description of your *issue*, suggested solution and other information

Trump signs bill undoing Obama coal mining rule

http://thehill.com/policy/energy-environment/319938-trump-signs-bill-undoing-obama-coal-mining-rule.

## Please follow (and edit) the guide below to expedite the bugtracker process.

- You will be asked a few questions:
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your pull request will actually look like

---

### Make sure you are using the *latest* version: pull latest commits before reporting any issues.
- [x] I've **verified** and **I assure** that I'm looking at the latest version of Trump Tracker.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) section.
- [x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/search?type=Issues) the bugtracker for similar issues including closed ones

**Comment by VirenMohindra** [comment]
Affects:

12.	First 100 Days: I will lift the restrictions on the production of $50 trillion dollars' worth of job-producing American energy reserves, including shale, oil, natural gas and clean coal.

92.	Environment: End the war on coal. (?)

**Comment by VirenMohindra** [comment]
Additional Sources:

http://dailycaller.com/2017/02/16/trump-signs-repeal-of-obama-coal-mining-regulations/

http://www.cnn.com/2017/02/16/politics/scott-pruitt-donald-trump-white-house-regulations/

http://www.washingtontimes.com/news/2017/feb/16/donald-trump-nixes-obama-regulations-coal-industry/?utm_source=RSS_Feedutm_medium=RSS

https://www.rt.com/usa/377639-trump-repeal-obama-coal-mining-rule/

http://www.foxnews.com/politics/2017/02/16/trump-overturns-bill-on-coal-mining-debris.html

**Comment by iProdigy** [comment]
Should this be closed? @VirenMohindra
