### ISSUE TITLE
Trump on Winning

### ISSUE THREAD

**Issue by iProdigy** [TrumpTracker/trumptracker.github.io#122]
In the following promise, Trump claims he's never going to lose.

        title: 'Start winning again. "We''re going to win so much -- win after win after win -- that you''re going to be begging me: ''Please, Mr. President, let us lose once or twice. We can''t stand it any more.'' And I''m going to say: ''No way. We''re going to keep winning. We''re never going to lose. We''re never, ever going to lose."'
        status: Not started
        category: Culture
        tags:
            - Trump
        comments: 'https://redd.it/5d81ss'
        sources:
            - 'https://web.archive.org/web/20161110005306/https://www.washingtonpost.com/news/post-politics/wp/2016/01/22/here-are-76-of-donald-trumps-many-campaign-promises/'

[/u/daerath](https://www.reddit.com/user/daerath) has [pointed out](https://www.reddit.com/r/trumptracker/comments/5d81ss/trump_start_winning_again_were_going_to_win_so/ddlc7qd/) that he lost the appeal case on his immigration ban and thus this promise should be marked as broken.

The promise itself is absurd so should it be removed altogether or marked as broken?

**Comment by VirenMohindra** [comment]
good idea, lets remove it

**Comment by iProdigy** [comment]
Included in #121.
