### ISSUE TITLE
Accessibility - Could you include an icon with the promise for colorblind users?

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#125]
### Description of your *issue*, suggested solution and other information

Could you include a icon with the promise for colorblind users? 

- From [Reddit user /u/rbevans](https://www.reddit.com/r/trumptracker/comments/5w0byl/suggestioncould_you_include_a_icon_with_the/)

## Please follow (and edit) the guide below to expedite the bugtracker process.

- You will be asked a few questions:
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your pull request will actually look like

---

### Make sure you are using the *latest* version: pull latest commits before reporting any issues.
- [x] I've **verified** and **I assure** that I'm looking at the latest version of Trump Tracker.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) section.
- [x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the trumptracker website)
- [ ] Site support request (request for adding support)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

**Comment by arbyruns** [comment]
thanks!

**Comment by MrLuit** [comment]
#144 will kind of fix this because the promise page will show the status in text.
