### ISSUE TITLE
Culture: Broken I will fight for the LGBT community. Broken Disagreement

### ISSUE THREAD

**Issue by EvilGamerX** [TrumpTracker/trumptracker.github.io#127]
### Description of your *issue*, suggested solution and other information

I think this item is way too broad to be considered a singular issue. Specifically looking at the bathroom issue, it seems to have been done not as a comment on the LGBT community but as a response to the Federal Government vs State Government, especially when there are certain people within the LGBT community who don't see this as an attack on them.

> "As President Trump has clearly stated, he believes policy regarding transgender bathrooms should be decided at the state level," the White House said in a statement.
- http://www.cnn.com/2017/02/22/politics/doj-withdraws-federal-protections-on-transgender-bathrooms-in-schools/

Not to mention that this can become another fluctuating issue where some actions can be taken as "Completing" this point, while others may be taken as "Breaking" it.

Honestly speaking I have no good idea to help mediate this, since this is not really a "Compromise" perhaps a "Complex" option which keeps a tally of everything done on that issue without assigning a "Complete" or "Broken" to them. 

## Please follow (and edit) the guide below to expedite the bugtracker process.

- You will be asked a few questions:
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your pull request will actually look like

---

### Make sure you are using the *latest* version: pull latest commits before reporting any issues.
- [x] I've **verified** and **I assure** that I'm looking at the latest version of Trump Tracker.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) section.
- [x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the trumptracker website)
- [ ] Site support request (request for adding support)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [x] Other

---

And as always, thank you for your contribution.

**Comment by iProdigy** [comment]
I think it's interesting that this administration likes to pull the "states' rights" card when it will benefit them/their ideology (rather than provide compassion for all people). 

Regardless: After withdrawing these protections, a fighter for the LGBTQ+ community would be taking actions to reinstate similar protections at the state-level, yet Trump has not done so.

**Comment by MrLuit** [comment]
If Trump shows that he cares and fights for the LGBT community, this promise will be marked as completed. This could be done by signing a bill that will allow for more transgender bathrooms, but it can also be done in a ton of other ways. This statement isn't "complex", it's actually really easy.
