### ISSUE TITLE
Automatic reply to @realDonaldTrump with update on # of promises with resp. status

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#129]
### Description of your *issue*, suggested solution and other information

As soon as a tweet is posted from his account, something along the lines of:

> @realDonaldTrump achieved 9 promises, broke 13, and had not started 138 during his 54 days in office. More @ https://trumptracker.github.io/

could auto-reply to him. Coul be set up on a Heroku server or locally.
---

### Make sure you are using the *latest* version: pull latest commits before reporting any issues.
- [x] I've **verified** and **I assure** that I'm looking at the latest version of Trump Tracker.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) section.
- [x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the trumptracker website)
- [ ] Site support request (request for adding support)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

And as always, thank you for your contribution.

**Comment by iProdigy** [comment]
Looks like a great idea to me!

We can utilize a wrapper around [Twitter's streaming api](https://dev.twitter.com/streaming/userstreams) to listen to Trump's tweets and then [use their REST api to post our tweets](https://dev.twitter.com/rest/reference/post/statuses/update). [Here](https://dev.twitter.com/resources/twitter-libraries) are some libraries that could be useful. 

I am familiar with Java and Python so I can assist in creation of such a bot.

**Comment by VirenMohindra** [comment]
I'm currently out of town and won't have service till Saturday. If you'd like to get started with this project you're more than welcome. I recommend you creating a new feature branch and then performing a PR once it's fully fledged out. One of the edge cases would be reaching the max tweet limit, so please keep that in mind when fleshing this not out. I've removed the compromised status because of this limitation.

**Comment by VirenMohindra** [comment]
Python is preferable!

**Comment by TrumpTracker** [comment]
https://github.com/TrumpTracker/UpdateTrump/commit/0ecf13d16466da220ddcc694b2e1de564b34bf41 closes this issue.
