### ISSUE TITLE
Trump promised to govern for all Americans

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#132]
### Description of your *issue*, suggested solution and other information

'I will be president for all Americans' — transcript of Donald Trump's election night victory speech

http://www.latimes.com/politics/la-na-pol-trump-election-night-speech-20161108-story.html

Submitted through the Typeform

---

I am not sure how we can keep a track of this promise.

**Comment by iProdigy** [comment]
In a literal sense, Donald Trump is already the president for all Americans.

**Comment by iProdigy** [comment]
His statement can also be interpreted to mean he will make decisions that are favorable for every American (impossible)...

**Comment by VirenMohindra** [comment]
Again, his promises are overarching to an extent that we cannot possibly quantify it into a specific status. I propose we mark as `compromised`.

**Comment by iProdigy** [comment]
Perhaps the promise shouldn't be added at all (?)...
