### ISSUE TITLE
[UPDATE] Refusing Presidential Salary

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#134]
### Description of your *issue*, suggested solution and other information

http://money.cnn.com/2017/04/03/news/trump-salary-national-parks/ - originally, you marked this promise as "broken." However, now we see that Trump really is refusing his presidential salary. This should be updated on your Trump Tracker!

- Davis

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) section.
- [x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the trumptracker website)
- [ ] Site support request (request for adding support)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

And as always, thank you for your contribution.

**Comment by iProdigy** [comment]
It's not exactly donating it to a charity that is partly decided by the press (as the White House said they would) but I'll still consider this promise as `in progress`.
