### ISSUE TITLE
No. 2 Institute a hiring freeze on all federal employees to reduce federal workforce through attrition (exempting military, public safety, and public health [UPDATE]

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#137]
Should this be **compromised** or **broken**?

### Description of your *issue*, suggested solution and other information

> White House Budget Director Mick Mulvaney announced the policy change in a briefing to reporters Tuesday.

- https://web.archive.org/web/20170412080116/http://www.npr.org/2017/04/12/523473051/trump-lifting-federal-hiring-freeze
- https://www.scribd.com/document/344966998/OMB-Memo-on-Reforming-the-Federal-Government-and-Reducing-the-Federal-Civilian-Workforce

**Comment by iProdigy** [comment]
I'd mark this promise as `in progress` for the time being and update to `compromised` if the administration is able to deliver.
