### ISSUE TITLE
Add Comment section linking to /r/trumptracker

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#14]
Add Comment section linking to /r/trumptracker on each policy on the right-hand side. Keep comments off the site to avoid toxicity + speed of the site.

**Comment by MrLuit** [comment]
I want to help you, but how do you want to implement this? Make a seperate thread for every promise?

If that's the case I will write that in no time.

**Comment by domingohui** [comment]
Comment section is important! :) 
I think to implement a comment section, we should decide on database  first. I notice alanfriedman is using JSON for the promises. Are we sticking to JSON for both promises, comments, etc? Or are we going to use something like SQLite?

@VirenMohindra when you said to keep comments off the site", did you mean just having comments in a separate database? Just like the promises and policies?

**Comment by VirenMohindra** [comment]
There is currently a whole subreddit dedicated to [/r/trumptracker](https://www.reddit.com/r/trumptracker/). We will be using Reddit as a platform to allow comments, so that the comments don't bog down the site, or add any bias/ toxicity onto a purely objective platform.
- Github is static so no database allowed, and I'm not planning on switching off this site anytime soon, unless anyone can offer a better solution. Along with SSL encryption and no hosting/ domain fees, GitHub pages seems like a viable option.

If you would like to contribute please see https://github.com/TrumpTracker/trumptracker.github.io/commit/76748c327a468df7e77558aa9e5fc4d97bd7528c

This is the proposed solution to allowing comments.

**Comment by VirenMohindra** [comment]
The only issues that crop are:
1. We are moving the discussion away from the site, so we will lose hits/ increase bounce rate.
2. We can't establish a community on TrumpTracker.github.io
3. Onboarding onto Reddit if people don't have an account, so another loop to jump through if people would like their voice to be heard.

Pros:
1. We don't collect any data/ personal information.
2. Purely static site {fast}
3. No toxicity/ bias on site.

**Comment by VirenMohindra** [comment]
single tab will look something like this, with the comment link on the right hand side.

![screen shot 2016-11-13 at 5 07 56 pm](https://cloud.githubusercontent.com/assets/10460518/20249260/d5601bc2-a9c3-11e6-8ab1-4ba4573d507c.jpg)

**Comment by MrLuit** [comment]
But what thread are people to comment on? Will there be a seperate thread for every promise Trump made?

**Comment by alanfriedman** [comment]
Why not implement [Disqus](https://disqus.com) or something similar?

**Comment by VirenMohindra** [comment]
@alanfriedman i'd rather not bog down the site, and keep comments off of it. Do you think disqus might be better? I'm trying to keep toxicity off the site.

**Comment by VirenMohindra** [comment]
@MrLuit yes there would be a separate thread for each policy. The only problem that will persist is when Reddit archives 6 month olf posts because of no comments, so I'll probably have to run an auto-mod, cron-job, or reddit bot to keep it open.

**Comment by MrLuit** [comment]
@VirenMohindra I am going to work on a comment system then. Is PHP fine or should I use javascript?

**Comment by VirenMohindra** [comment]
We're hosted on GitHub pages and aren't moving anywhere soon. Php won't work -- lets try out JavaScript?

**Comment by alanfriedman** [comment]
I like what they've done [here](https://govtracker.co.uk/#main_center) with Disqus comments on the promise's page.

**Comment by MrLuit** [comment]
I'm currently making a seperate thread for every police via /u/TrumpTracker (bot). Can the account have moderator please? The problem is that there will be 198 threads when I'm done, so the subreddit will be a bit spammed.

When I'm done I will update data.json with all the correct URL's.

**Comment by domingohui** [comment]
@alanfriedman  @VirenMohindra  I'm not quite familiar with Disqus. but +1 for the Disqus implementation. it seems like a great way to build a community. I'm not sure if it's gonna work a static site on Github tho. 
I would love to contribute building it.

**Comment by MrLuit** [comment]
Adding Reddit comments with #37 👍

**Comment by MrLuit** [comment]
Reddit comments are added, I think this issue needs to be closed.

**Comment by VirenMohindra** [comment]
Sounds good, regarding the YAML issue, I was thinking you could wget the
live site and then scrape that data? Since it does get converted to json
online.
