### ISSUE TITLE
Mark every in progress-policy as broken in 100 days category

### ISSUE THREAD

**Issue by MrLuit** [TrumpTracker/trumptracker.github.io#142]
### Description of your *issue*, suggested solution and other information

Every 100 days promise that is now on 'in progress' should be marked as broken until it is executed, then it should be compromised.

---

### Make sure you are using the *latest* version: pull latest commits before reporting any issues.
- [x] I've **verified** and **I assure** that I'm looking at the latest version of Trump Tracker.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) section.
- [x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/search?type=Issues) the bugtracker for similar issues including closed ones

**Comment by MrLuit** [comment]
I will try to do this tomorrow but I'm not sure if I can do this alone.

**Comment by VirenMohindra** [comment]
Can we add a clause to the 100 days promise so that people know and understand that if the president does complete any of the aforementioned promises, we will mark it as `compromised`?

**Comment by MrLuit** [comment]
24a5799ca8b75f1057e8b9cdb1a74375dac5fafd
