### ISSUE TITLE
[SUGGESTION] Seperate title and description

### ISSUE THREAD

**Issue by MrLuit** [TrumpTracker/trumptracker.github.io#145]
### Description of your *issue*, suggested solution and other information

Just an idea.

Some titles are really long and some titles are way too short. By creating a seperate 'title' and 'description' there would also be more space on the homepage. The description will only be shown on the promise page.

---

### Make sure you are using the *latest* version: pull latest commits before reporting any issues.
- [x] I've **verified** and **I assure** that I'm looking at the latest version of Trump Tracker.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) section.
- [x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/search?type=Issues) the bugtracker for similar issues including closed ones

**Comment by VirenMohindra** [comment]
Great idea: how do we standardize the length of promises and what should overflow into the description? Do you have anything in mind?

**Comment by MrLuit** [comment]
If we want the full title to fit inside a h2 without wrapping to a newline, the limit is ~69 characters. That is very short but I think it will be a good guideline. This will also make the 'prettyurl' truncate of 100 characters unnecessary.

The twitter limit is ~62 characters if we include the hastags and promise no: etc.

**Comment by VirenMohindra** [comment]
69 characters at what viewport (window browser size)?
I'll keep this in mind but I think the newline will probably end up happening anyways.

A key point we need to focus on is mobile responsiveness.
I'll take a look at the `data.yaml` tonight

**Comment by MrLuit** [comment]
I meant 89 at 1920x1080
