### ISSUE TITLE
Political bias of contributors on time independent promises

### ISSUE THREAD

**Issue by timcason** [TrumpTracker/trumptracker.github.io#148]
### Description of your *issue*, suggested solution and other information

I was hoping that this tracker would be something that is a pure data driven tracker, but more and more i have noticed that updates and contributions seem a little too hastily accepted as 'Broken' promises.  I am not advocating for anyone to agree or disagree with the proposed promises, however it has come to a point that I would rather source tracking promises from another source.

Source - http://www.politifact.com/truth-o-meter/promises/trumpometer/browse/

I would propose that this group create & train machine learning neural net to confirm with news sources that status of any particular promise after scanning and removing bias.  Humans are inherently flawed in being able to make unbiased decisions.  

Here are a few non-binary statuses for promises that are already marked as Broken that could be debated as 'Unconclusive'.

78.	Economy: - Broken - Provide more funding for police training. 
87.	Government: - Broken - Stop spending money on space exploration until the United States can fix its potholes. Encourage private space-exploration companies to expand. 
141.	Health: - Broken - Save Medicare, Medicaid and Social Security without cutting benefits. 
174.	Education: - Broken - Get rid of Common Core because it's "a disaster" and a "very bad thing." Trump says he wants to give local school districts more control and might even eliminate the Department of Education. 

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the trumptracker website)
- [x] Site support request (request for adding support)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

**Comment by VirenMohindra** [comment]
Could you provide sources for the `Broken` promises that you've listed which might mark it as inconclusive?

**Comment by MrLuit** [comment]
Here's my thought on this: since we have added Reddit comments support all reasoning behind marking something as broken can be stickied to the top of the comments. This was not possible earlier.

**Comment by MrLuit** [comment]
Update: I have added a status_info to data.yaml to display reasoning behind marking something as broken or achieved or whatever :)
