### ISSUE TITLE
[REQUEST] Create a category for 100-day promises which were completed, just not in the 100 days.

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#149]
### Description of your *issue*, suggested solution and other information

Create a category for 100-day promises which were completed, just not in the 100 days. Trump has had a really hard time getting people approved. There are also some promises where they were just opening-deal positions. Consider China and what looks like a good working relationship now and his reversal on the Putin position.

Sent by Typeform by Toby

---

### Make sure you are using the *latest* version: pull latest commits before reporting any issues.
- [x] I've **verified** and **I assure** that I'm looking at the latest version of Trump Tracker.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) section.
- [x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/search?type=Issues) the bugtracker for similar issues including closed ones

**Comment by MrLuit** [comment]
But this is exactly what 'compromised' was made for.

Edit: Don't forget that a comment is stickied to every 100 days promise that was marked as 'broken' because they were not completed in 100 days.

**Comment by MrLuit** [comment]
Update: I have added a status_info to data.yaml :)
