### ISSUE TITLE
[FIX] Gray "compromised" appears blue on my ipad. cannot tell it from blue.

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#150]
### Description of your *issue*, suggested solution and other information

Gray "compromised" appears blue on my ipad. cannot tell it from blue.

Sent by Typeform by Toby

Referencing #97 and #125 this is becoming a real problem.
---

### Make sure you are using the *latest* version: pull latest commits before reporting any issues.
- [x] I've **verified** and **I assure** that I'm looking at the latest version of Trump Tracker.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) section.
- [x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/search?type=Issues) the bugtracker for similar issues including closed ones

**Comment by MrLuit** [comment]
We could change it to #b5cede

![](https://i.imgur.com/vMkKQsF.png)
