### ISSUE TITLE
Formatting Errors of Table

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#23]
Formatting errors examples on site:

1. Against the H-1B visa program.

1. Pick Supreme Court justices who are "really great legal scholars."
1. It's unclear where Trump stands on "first use," or if he'd be willing to strike first.
1. Overturn Roe v. Wade, then let states decide it.	
1. Defund Planned Parenthood.
1. It doesn't matter, people make mistakes.	
1. It's OK that Trump's running mate voted for the Iraq war, but it's not OK that Clinton did.
1. Get rid of Common Core because it's "a disaster" and a "very bad thing." Trump says he wants to give local school districts more control and might even eliminate the Department of Education.

**Comment by VirenMohindra** [comment]
> On November 8th, Americans will be voting for this 100-day plan to restore prosperity to our economy, security to our communities, and honesty to our government. This is my pledge to you. And if we follow these steps, we will once more have a government of, by and for the people.  
> 
> Trump Tracker will be following each and every policy to see they get fulfilled.

this was left out of the data.json, add it back in.

**Comment by VirenMohindra** [comment]
@alanfriedman do you think you might know why some of the points are so haphazardly aligned on the site? 

Example: 
![screen shot 2016-11-14 at 2 17 00 pm](https://cloud.githubusercontent.com/assets/10460518/20279070/0db1085e-aa75-11e6-8c9e-25cd5bb8747e.jpg)

I think it might be because only one of the policies have a comment section, and it hasn't been implemented site-wide.

**Comment by alanfriedman** [comment]
Probably because the JSON file has some formatting issues. It's easy to cleanup if you want to push a fix. Just edit `_data/data.json`.

**Comment by VirenMohindra** [comment]
I'll fix it, thank you.

**Comment by VirenMohindra** [comment]
@alanfriedman modifying the JSON file doesn't seem to fix it. I've tried minifying it and removing all formatting whatsoever but it doesn't seem to fix the issue.

**Comment by domingohui** [comment]
I tried the Jekyll code and the css. But it didn't work either... What browser are you using?
I'm using Safari 10.0.1 on Mac.

**Comment by VirenMohindra** [comment]
@domingohui Latest version of Chrome Version 54.0.2840.98 (64-bit)
Problem persists on Safari Version 10.0.1 (11602.2.14.0.7)
Mozilla 40.0.3

**Comment by alexanderankin** [comment]
td's inside of tr's need a property { width: 100% } and that seems to be the missing puzzle piece to making the table work, at least on my machine.

apparently not, but here's what is true of that: if you add the width property to one of the table data (td) tags instead a table row (tr) via google dev console, the whole section straightens itself out. by section i mean "contract with american voter" and its 6 points. and then again for next section, and the rest of the page straightens out. once i figure out how to turn into code, will be PR

**Comment by alexanderankin** [comment]
the hacky version to fix the bug:

``` js
$('html > head').append( $('<style>tbody > tr:nth-child(1) > td:nth-child(2) { width:100%; }</style>') )
```

**Comment by VirenMohindra** [comment]
sounds good, keep me updated! i'll check locally too.
experiencing major outages right now, will push your PR once everything normalizes

**Comment by VirenMohindra** [comment]
keeping this issue open until we can figure out a more robust solution

EDIT: Tables are separate for each policy heading, which messes up alignment across all tables.
https://github.com/twbs/bootstrap/issues/21151
