### ISSUE TITLE
Twitter share integration for each policy, so once broken we can mention Donald Trump

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#33]
Thoughts? might be too far-fetched.

**Comment by domingohui** [comment]
Sounds great! It's not too hard to implement. One of the pros: it promotes and builds a community every time someone tweets a policy whether it's broken or actually honoured. Also, there isn't too much overhead to the website.

I don't see too much downside to it. One might be the redundancy that comes with the integration if people don't actually end up using it, but we can remove it then.

**Comment by aleross** [comment]
+1. I would mention Donald Trump when a policy is honored as well in order to keep things balanced.

**Comment by VirenMohindra** [comment]
Logic:

```
if (status="broken" || status="completed" ) {
 diplay twitter integration for specific policy
}
```

so if `status="notCompleted"`, it won't show.

Maybe we have a different twitter message for `broken` and `completed` ?

**Comment by alexanderankin** [comment]
[check it out](https://gist.github.com/alexanderankin/d39893193d8769ca1b9df77e588a2fd3) - I included an index.htm you can drop in overwriting the one in the repository, as well as the diff of changes, what do you guys think?

right now it is set to display the twitter button `{% if point.status == "notStarted" %}` so that the behavior is visible without additional steps for testing purposes. basically it puts a twitter logo next to the comments button and when you click it generates a message and links to share it on twitter.

Here is a [comparison](http://imgur.com/a/h2AuD/layout/grid) of what it looks like with/without on mobile and in general. I think the bird should maybe be replaced a button that looks like the twitter "Tweet" button from image two in the comparison. Input?

**Comment by alexanderankin** [comment]
also i wrote the code for good wording, but i didnt really put much thought into the wording, again looking for suggestions.

**Comment by VirenMohindra** [comment]
Brilliant work, just refactoring and fixing the code right now.

Referencing commit: ced99ef

## Few intricacies I've noticed:
1. **Increment variable outputting text abnormally:** `{% increment issue_number %}` outputs onto the table so I found a fix. You just need to comment out the line. Jekyll will ignore the comment tags and run the Liquid syntax, but not output any code and still increment the policy numbers.

2. **NEEDS A TEMP/ FULL FIX:** Encoding issues with double quotes, the parser immediately stops at the first double quote. We either need to remove all of these instances or add entity references. 

3. **Formatting errors:** more table column divisions than column divisions in the heading section, and it crushed the policy text which didn't look pleasing on mobile. I've fixed both by moving the twitter button on top of the comment button and adding conditional statements. Removed blue tweet color style for consistency.

4. **Clean up:** Removed unnecessary `<p>` tags which covered the link, replaced with `<div>` tags and centered the `<i>` class.

5. **Lengthening of tweet for increased policy exposure:** Removed mention of my Twitter username to further increase character limit, and extended policy text to utilize the full amount of Twitter's character limit.

## Other Thoughts:

1. **TL;DR:** Only thing left with tweets are the double quotation encoding issues, which can be an easy find/ replace. Discussion on Gitter.

2. Major issues with [W3 Validator](https://validator.w3.org/), ~500 errors because of the character entities. Will need to fix this **ASAP**.

3. Are we sticking to displaying tweet button _always_ or only for status `broken` and `achieved`? I like the consistency as of now and it might look jagged and irregular. We might get more exposure if it always stays there. Thoughts on Gitter.

PS: Reached 6k LOC of outputted HTML. Will probably need a GitHub pages minification plugin which is compatible. Great job everyone!

**Comment by VirenMohindra** [comment]
Major props to @alexanderankin.

**Comment by MrLuit** [comment]
I made some improvements to the tweet-function:

- e8497a06bef8043c06796a4d6ef4e4653bf20f21 Fixes the button
- e8295ce546bf1b2156cc04a8ddd9babac0f3569d Fixes the button without using another `<td>`
- 3c2bf4cf78cb38b8b8722240fa57921ecce020d6 Adds url encoding to all the tweets
- 376da37586fac73466195a4cd986a79adb46920a Changes the tweet length to fit exactly 140
- 5493ddd4c16634244ed124d705a76d5bb3e97696 Changes the tweet length to fit exactly 140
- bfdb669b88d9c0468e38f7f9e2d36a1bea2c77dc Changes the tweet length to fit exactly 140
- 819a47fde7051ee41f33b8c4412ab1a5f0c0cbc1 Changes the tweet length to fit exactly 140

The last 4 commits are all improvements on the character limit. I think that sums it up for this issue?
