### ISSUE TITLE
Search doesn't display progress of policy completion if it is broken or not in Main Nav Search

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#39]
to test - change `status` in _data.json to one of the following options and then search for it using `main-nav`.

`broken` => `danger` class
`achieved` => `success` class

paging @MattSandy

**Comment by kylehodgetts** [comment]
How many different status' are there:
- broken
- achieved
- notStarted

That's it, right?

**Comment by VirenMohindra** [comment]
thats it, yes!

Statuses:
`broken` => `danger` class
`achieved` => `success` class
`notStarted` => blank class

**Comment by kylehodgetts** [comment]
Okay, working on it now :)
