### ISSUE TITLE
Several items are not promises

### ISSUE THREAD

**Issue by jamesscottbrown** [TrumpTracker/trumptracker.github.io#4]
Several items (particularly on the 'International' tab) are statements of Trumps' beliefs, rather than promises about what he will do. For example,

* "Israel is the state of the Jewish people, who have lived in that land for 3,500 years. The State of Israel was founded with courage and determination by great men and women against enormous odds and is an inspiration to people everywhere who value freedom and human dignity."
* "Clinton voted for the war, so she has bad judgment."

**Comment by VirenMohindra** [comment]
I closed this issue, but we are definitely working on cleaning all of this. Thank you for your suggestions.
