### ISSUE TITLE
onClick of  Not Yet Started, In Progress, Achieved, and Broken, corresponding list is displayed.

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#40]
![screen shot 2016-11-16 at 2 15 37 am](https://cloud.githubusercontent.com/assets/10460518/20338036/93384388-aba2-11e6-9aa3-4dc2764e102f.jpg)

**Comment by VirenMohindra** [comment]
Definitely want to move this to v3.0, since this isn't a priority.

**Comment by ek68794998** [comment]
Looks like a duplicate of this was created at #83. Is v3 still in the works?

**Comment by VirenMohindra** [comment]
@ekumlin yes it is
