### ISSUE TITLE
Opendata Production

### ISSUE THREAD

**Issue by iltempe** [TrumpTracker/trumptracker.github.io#44]
If is possible link all raw data of promises on the website in order to make them open. Should be nice to have also Creative Commons licence to define the term of reuse.

**Comment by VirenMohindra** [comment]
All data is currently hosted in the data/_data.yaml.

As far as reusing the data goes, I've sourced all the text from public sites, no bias in itself... Not sure what are the terms regarding modification.

Will definitely add an Open Source link on the footer though.
