### ISSUE TITLE
A Spanish Version

### ISSUE THREAD

**Issue by jesusmtzarvizu** [TrumpTracker/trumptracker.github.io#49]
A Spanish Version of the **_data/data.yaml** file

**Comment by jesusmtzarvizu** [comment]
I am working on it

**Comment by VirenMohindra** [comment]
Fantastic work. The only issue is that I wouldn't be able to double check your work because I don't know how to speak/ read in Spanish.  Maybe one of your friends can chime in too?

**Comment by VirenMohindra** [comment]
@alanfriedman as we can see here he has created a separate `data.yaml` for the spanish version. Should it be incorporated into one for maintenance and for ease of pulling the data or keep those two files separate?

@jesusmtzarvizu if you do find any duplicates/ spelling errors in the English version please feel free to let me know. It'll make our job much easier.

**Comment by alanfriedman** [comment]
We should definitely keep them separate, using a naming convention like `data-es_ES.yml`. My first thought is checking a `locale` query param in the URL and choosing the data file based off that (`http://trumptracker.github.io?locale=es_ES` => `data-es_ES.yml`).

While we're at it, we should really translate the entire site. You could throw all strings in the data file for now.

**Comment by VirenMohindra** [comment]
Seems reasonable - maintenance will suck when adding new policies though.

**Comment by alanfriedman** [comment]
We can use automated translation (Google translate, etc) until someone has time to do it manually.

**Comment by MrLuit** [comment]
If we make a spanish translation, a translation for every language should be allowed. But is it actually that useful?

**Comment by VirenMohindra** [comment]
Only implementing an English and Spanish version because they're the two most spoken languages in the US.

**Comment by alanfriedman** [comment]
I think it's definitely useful. We can start with Spanish and if someone wants to submit a new language they just add a new data.yml file.

**Comment by MrLuit** [comment]
I think we should indeed draw the line at English and Spanish, because if a new policy is added, we have to update every language file otherwise it will be outdated.

**Comment by alanfriedman** [comment]
Sounds good

**Comment by iProdigy** [comment]
Puedo hablar español. What's the status on translations @jesusmtzarvizu ?

**Comment by jesusmtzarvizu** [comment]
I am Sorry I was enrolled on a Big project and my time is limited now so I didnt translate it.

**Comment by VirenMohindra** [comment]
@iProdigy any chance you can work on this?

**Comment by iProdigy** [comment]
It would be my pleasure @VirenMohindra.

In a week my schedule will be more free to allow me to begin translating. I also want to note that while I am not a native speaker of Spanish, I am fluent with five years of experience...

**Comment by VirenMohindra** [comment]
Sounds good, thank you!

If you do find any repetitions in the English version of the `data.yaml` please feel free to make PR's to join them!

**Comment by myyk** [comment]
I would like to help out with this. I also have a non-technical Spanish speaking friend that is willing to help out with translations.

**Comment by VirenMohindra** [comment]
@myyk perfect! Please feel free to perform any PR's
