### ISSUE TITLE
RSS Feed?

### ISSUE THREAD

**Issue by pavellishin** [TrumpTracker/trumptracker.github.io#5]
An RSS feed would be excellent for updates.

**Comment by MrLuit** [comment]
I know it's not perfect, but you could use https://github.com/TrumpTracker/trumptracker.github.io/commits/master.atom for an RSS feed of all commits.

**Comment by pavellishin** [comment]
Yeah, that's not great - because it may not reflect actual content changes, but rather code changes. ("oh, cool, new favicon.")

**Comment by VirenMohindra** [comment]
Whenever we update a policies status, we can scrape it off the site and
publish the results in a RSS feed? Not a clean cut solution but it could
work. Just need to always run something in the background

**Comment by MrLuit** [comment]
I was actually trying to do something with the Github API, like getting the latest commits where data.yaml has been changed but the api rate is really low so it probably won't work.

**Comment by pavellishin** [comment]
Y'all could use a git hook to automatically check for changes to data.yaml, and modify the rss feed as well - but I believe you'd have to keep those synced and make sure each collaborator had it in the `.git/hooks` directory.

I don't know if there's git magic to keep those versioned and running as well.

**Comment by MrLuit** [comment]
https://github.com/TrumpTracker/trumptracker.github.io/commits/master/_data/data.yaml.atom

You can use this url to get an RSS feed of all changes to _data/data.yaml 👍

**Comment by VirenMohindra** [comment]
![screen shot 2016-11-18 at 2 23 44 pm](https://cloud.githubusercontent.com/assets/10460518/20443395/a1d5c11e-ad9a-11e6-90b6-7528e0f3a6bb.jpg)

The problem with subscribing to commits is that we don't see the changes, so might have to explicitly state it in the `-m "commit message"`  when we update a policy

something along the lines of "BROKEN - Propose a Constitutional Amendment to impose term limits on all members of Congress"

**Comment by MrLuit** [comment]
Yeah we'll just have to do that. I don't see any other easy way, but if someone wants to make that I'm open to it.

**Comment by MrLuit** [comment]
I just finished the RSS feed. (I have also added the RSS button to the main page)

[Here is](https://luithollander.nl/trumptracker/rss.php) the RSS feed, [here is](https://github.com/MrLuit/TrumpTrackerRSS) the github source. 

Let me know if you have any suggestions! :)
