### ISSUE TITLE
Adding new policies

### ISSUE THREAD

**Issue by MrLuit** [TrumpTracker/trumptracker.github.io#52]
To Do

1. From Google : Trump issues

2. https://www.donaldjtrump.com/issues

3. https://www.donaldjtrump.com/policies/

**Comment by VirenMohindra** [comment]
1. Sign FADA https://www.donaldjtrump.com/press-releases/issues-of-importance-to-catholics
2. Trump vowed to end the Clean Power Plan
3. Ban Muslim Brotherhood affiliated organizations
4. Trump supports an audit of the FED http://www.realclearpolitics.com/video/2016/09/07/ron_paul_donald_trump_wants_to_audit_the_federal_reserve.html

**Comment by MrLuit** [comment]
3ff6acdba8a9c2b57f2d868f818becc8a817320a

**Comment by VirenMohindra** [comment]
1. Just as some further input, I'd love to see an entry for his promise to demand that members of NATO pay the US to continue having US protection.

**Comment by VirenMohindra** [comment]
Will need to remove this
![nkie5fu](https://cloud.githubusercontent.com/assets/10460518/20466209/c22f0738-af3c-11e6-8463-029f96950359.png)

**Comment by MrLuit** [comment]
793f438

Way ahead of you ;)

**Comment by VirenMohindra** [comment]
1. Assign a special prosecutor to start a criminal investigation into Hillary Clinton. http://time.com/4524459/presidential-debate-donald-trump-special-prosecutor/

**Comment by MrLuit** [comment]
0ca52b99ad0cd4fcfa1819d3bd3cf96e11a9181e

**Comment by VirenMohindra** [comment]
Trump will not prosecute Hillary Clinton. http://www.bbc.com/news/world-us-canada-38069585

**Comment by MrLuit** [comment]
282 promises in one list:

[‘I will give you everything.’ Here are 282 of Donald Trump’s campaign promises.](https://www.washingtonpost.com/politics/i-will-give-you-everything-here-are-282-of-donald-trumps-campaign-promises/2016/11/24/01160678-b0f9-11e6-8616-52b15787add0_story.html) @illepic #67
