### ISSUE TITLE
The motherload of promises

### ISSUE THREAD

**Issue by illepic** [TrumpTracker/trumptracker.github.io#67]
282 promises in one list:

[‘I will give you everything.’ Here are 282 of Donald Trump’s campaign promises.](https://www.washingtonpost.com/politics/i-will-give-you-everything-here-are-282-of-donald-trumps-campaign-promises/2016/11/24/01160678-b0f9-11e6-8616-52b15787add0_story.html)

I'd like to hear back on the data structure from #66 before making a PR to integrate all these. Note, use this article as one source, but also ensure the linked sources are also included (PR #66 handles multiple sources per promise). I'd recommend using an archive.org link, especially on sites that are prone to change.

**Comment by MrLuit** [comment]
Please refer to #52 :)
