### ISSUE TITLE
Archive.org

### ISSUE THREAD

**Issue by iltempe** [TrumpTracker/trumptracker.github.io#69]
Please note this archive of videos http://archive.org/details/trumparchive&tab=about

**Comment by MrLuit** [comment]
Hi there :) 

Thanks for pointing this out, we will be able to use this in the future, instead of uploading every video to our own youtube channel. Waiting till @VirenMohindra sees this.

**Comment by patcon** [comment]
Since this seems to fall under the general gist of this issue, might be good to offer link to archive.org mirror for all sources, just in case things disappear or move around (not likely, but meh)

**Comment by MrLuit** [comment]
I spoke to @VirenMohindra and it seems very likely that we will adapt archive.org as our main sources in the near future.

**Comment by VirenMohindra** [comment]
0ea1b9e028450ebe86eeab5529ccb7bbfb6fcf8e + archive.org will be sending up deep-linked videos to add to our citations
