### ISSUE TITLE
What's the current planned way to manage Promises?

### ISSUE THREAD

**Issue by aflashyrhetoric** [TrumpTracker/trumptracker.github.io#7]
I'd like to contribute as this seems like an interesting project - were you planning to include some sort of CMS to manage the promises? I think a flat-file CMS might be good here - simple and easy to manage.

**Comment by VirenMohindra** [comment]
Do you have any ideas for flat file CMS's? I'm not sure which one to use.

**Comment by aflashyrhetoric** [comment]
If you're comfortable with PHP (or want an excuse to dive in), [Grav](https://getgrav.org/) is a powerful option. I am using it for a website right now and it's lovely. But you may want to spend a day purely reading the docs over and over instead of trying to build something right away. (It's also one of the most popular flat file CMSes out there.)

**Comment by VirenMohindra** [comment]
I really want to keep it on the .github.io domain because I automatically get SSL encryption and the site won't crash under any stress. If `Grav` is php I don't think I'll be able to use it on Github because it's statically generated sites/ or templating system engines only right?

**Comment by aflashyrhetoric** [comment]
Ah in that case maybe Jekyll or Hugo. I've used both and loved both, although I'm more into Hugo now. They are SSGs but if we use Flyleaf (I think that's what it was called) on top of it we can have a pretty decent CMS-esque experience. I understand your decision though - better to let Github handle the security for a site like this, ahaha.
