### ISSUE TITLE
Use a more "dignified" photo of Trump

### ISSUE THREAD

**Issue by patcon** [TrumpTracker/trumptracker.github.io#71]
Not sure your politics, but I would think it might be worth using a Trump photo on the front page that is a little more neutral. The [current photo](https://imgur.com/OmQ5Xbx.png) seems to want to convey him as "unpresidential", and will likely make anyone who sympathizes with him (ie. 48% of voters) assume the site is biased against him.

Let's make a small change that will make those folks a little bit more likely to stay on the the website :)

**Comment by VirenMohindra** [comment]
Good suggestion. Might remove the picture itself and keep content only. Refer to https://trumptracker.github.io/revamp

Did you take a screenshot before the whole site loaded? I can't see the dynamic content loaded + favicons (check days till inauguration etc)

**Comment by patcon** [comment]
Cool! Ah, oops. pasted the wrong screencap -- that one was for the another issue *about* the exact thing you pointed out. just forgot to submit it :)

doing now.
