### ISSUE TITLE
Use placeholder when loading dynamic data

### ISSUE THREAD

**Issue by patcon** [TrumpTracker/trumptracker.github.io#72]
Sometimes the page can take awhile to load. My first load (admittedly when my computer was chugging along) took 10 seconds. This was what I saw during that time: https://imgur.com/OmQ5Xbx.png

Would be great if the placeholder text was something more indicative of the loading process :)

Just thinking dimmed text saying something like "loading..." or whatever

**Comment by MrLuit** [comment]
We will likely implement a simple loading text in the new version of trumptracker. Thanks for submitting this idea.

**Comment by VirenMohindra** [comment]
6981fd171c77b2512d10738fadf85ef222eba160 fixes this for inauguration date and days in office.

**Comment by VirenMohindra** [comment]
442ce1e113fc0ba87799220d7ad5b59574cf481e doesn't require a load for promises/ policies because of the way the YAML data is injected into the site.
