### ISSUE TITLE
"Submit a new policy" button is not working

### ISSUE THREAD

**Issue by domingohui** [TrumpTracker/trumptracker.github.io#73]
I don't know if this came up before... Sorry if that's the case! The typeform window didn't pop up on my Chrome, IE or my phone. I can try fixing it tonight or tomorrow if no one wants it. (The actual form seems to be working tho)

**Comment by VirenMohindra** [comment]
Strange -- Works on [/revamp](https://trumptracker.github.io/revamp) but not on the main page.

Working on a fix
