### ISSUE TITLE
Technicalities involving time constraints

### ISSUE THREAD

**Issue by HysMagus** [TrumpTracker/trumptracker.github.io#76]
How technical will Trump Tracker be on the president's promises? Will promises involving time constraints which are directly mentioned like on the "first day" be held to that time in terms of completion status?
I really like this project idea! Will future promises made be added on or is it just campaign promises?

**Comment by VirenMohindra** [comment]
Future promises will be added as his term continues. 

We will be adhering to time constraints since that is what he planned out himself (eg 100 days).
After that the progress will be either `inProgress` or `Compromised`.
