### ISSUE TITLE
Open site up to all actions, not just limited to promises

### ISSUE THREAD

**Issue by evvvritt** [TrumpTracker/trumptracker.github.io#78]
Hi, I think this is a great project and thank you for developing it. I wonder if expanding it to track all of this actions, not just his promises would add value. It could track his executive actions, legislation, deals etc and the promises list could still be maintained and cross referenced with that "feed". A centralized, chronological and annotated list would be highly valuable in this noisy media landscape! 👍

**Comment by MrLuit** [comment]
Yes the site is meant as platform for actions and promises, policies in general. If you can find sources of things we missed, feel free to let us know.
