### ISSUE TITLE
Labels clickable?

### ISSUE THREAD

**Issue by individual8** [TrumpTracker/trumptracker.github.io#82]
Can you make labels like In Progress/Achieved/Broken clickable and therefore acting as filters? Like the TrudeauMetre does?

**Comment by plondon** [comment]
This seems to be on the TODO list (9)

> Implement functionality to let me click on the "broken", "in progress", "achieved" categories so I can see which things fall into those categories.

Is this a WIP? @VirenMohindra

**Comment by VirenMohindra** [comment]
please refer to #81 , this issue has been closed since v2 which is hosted on https://trumptracker.github.io/revamp has these features.
