### ISSUE TITLE
Sort by Broken, Achieved, or In Progress

### ISSUE THREAD

**Issue by frosteeze** [TrumpTracker/trumptracker.github.io#83]
Can we have a feature to sort by what status the promise is? Thanks.

**Comment by ek68794998** [comment]
Agreed. Would be nice to be able to click one of the "status" rows and see all promises of that type.

![image](https://cloud.githubusercontent.com/assets/1350074/22218782/360892b2-e15d-11e6-9075-480235304948.png)

Either that, or include the status in the search box (so typing "Broken" shows all broken promises, e.g.).

**Comment by VirenMohindra** [comment]
Yes, please look at previous PR's, its in the works.
