### ISSUE TITLE
Add contributor guide to readme

### ISSUE THREAD

**Issue by alanfriedman** [TrumpTracker/trumptracker.github.io#88]
We should add information like available status codes to the readme to help people more easily contribute.

**Comment by MrLuit** [comment]
In the new revamp.yaml the status are displayed in a better way :)

    Not started:
        color: info
        icon: hourglass-start
    In progress:
        color: warning
        icon: cogs
    Achieved:
        color: success
        icon: check-circle-o
    Broken:
        color: danger
        icon: ban

**Comment by VirenMohindra** [comment]
@MrLuit I think he meant making a CONTRIBUTING.md so people get a list of options when they're submitting an issue or PR. It'll be done in the next hour or so.

**Comment by MrLuit** [comment]
Done, closing this one.

31f54c35e35e9b02b8c3286d5580ffff04e5c18f
