### ISSUE TITLE
Consider adding "Partially Achieved".

### ISSUE THREAD

**Issue by ghost** [TrumpTracker/trumptracker.github.io#93]
Trump never got rid of gun-free zones in schools on his first day. His promise is never going to be completely fulfilled. However, he could still accomplish it a few days from now.

I propose adding the category "Partially Achieved" for promises he never completely fulfilled, but never completely broken.

**Comment by MrLuit** [comment]
I agree, but I think we should call it 'Compromised'.

**Comment by ghost** [comment]
That makes more sense! Let's rate it:

Thumbs up for "Compromised", thumbs down for "Partially Achieved", and Confused for something else

**Comment by VirenMohindra** [comment]
442ce1e113fc0ba87799220d7ad5b59574cf481e added compromised
